name: Terraform

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Terraform Init
        id: init_pullrequest
        if: github.event_name == 'pull_request'
        run: terraform -chdir=environments/dev init -backend-config ../../conf/backend-dev.tf  

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: ls | terraform -chdir=environments/dev plan -no-color

      - name: Add Plan Comment
        id: comment
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const output = `<details><summary>Show Plan</summary>
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\``;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Init
        id: init_push
        if: github.event_name == 'push'
        run: terraform -chdir=environments/dev init -backend-config ../../conf/backend-dev.tf  

      - name: Terraform Apply
        id: apply
        if: github.event_name == 'push'
        run: terraform -chdir=environments/dev apply -auto-approve
